"use client";

import { useEffect, useRef } from "react";

/**
 * Interactive API docs (Swagger UI) for the route surface documented in
 * API.md. Reads the spec from /openapi.json (a static file in `public/`,
 * generated by `npm run docs:build` whenever routes change — see
 * scripts/build-openapi.mjs's header comment).
 *
 * Served entirely from locally vendored assets (public/swagger-ui/,
 * copied from the swagger-ui-dist npm package by `npm install`'s
 * postinstall hook — see scripts/sync-swagger-ui-assets.mjs) rather than
 * a CDN, so this page works offline and has no runtime dependency on any
 * third-party host.
 *
 * Admin routes are exercised with real cookies: log in via
 * POST /api/admin/auth/login right here in the UI (Admin — Auth section)
 * and the browser attaches the resulting admin_session cookie to every
 * subsequent "Try it out" call automatically, since this page is served
 * from the same origin as the API.
 */
export default function ApiDocsPage() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;

    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = "/swagger-ui/swagger-ui.css";
    document.head.appendChild(link);

    const script = document.createElement("script");
    script.src = "/swagger-ui/swagger-ui-bundle.js";
    script.async = true;
    script.onload = () => {
      if (cancelled) return;
      type SwaggerUIBundleFn = {
        (opts: Record<string, unknown>): void;
        presets: { apis: unknown };
        plugins: { DownloadUrl: unknown };
      };
      const w = window as unknown as { SwaggerUIBundle: SwaggerUIBundleFn };
      const SwaggerUIBundle = w.SwaggerUIBundle;
      SwaggerUIBundle({
        url: "/openapi.json",
        domNode: containerRef.current,
        deepLinking: true,
        presets: [SwaggerUIBundle.presets.apis],
        plugins: [SwaggerUIBundle.plugins.DownloadUrl],
        layout: "BaseLayout",
        docExpansion: "list",
        // Same-origin cookie is attached automatically by the browser;
        // this just makes sure fetch() doesn't drop it.
        requestInterceptor: (req: { credentials?: string }) => {
          req.credentials = "same-origin";
          return req;
        },
      });
    };
    document.body.appendChild(script);

    return () => {
      cancelled = true;
      document.head.removeChild(link);
      document.body.removeChild(script);
    };
  }, []);

  return (
    <main style={{ fontFamily: "system-ui" }}>
      <div style={{ padding: "1rem 1.5rem", borderBottom: "1px solid #e5e5e5" }}>
        <strong>Restaurant Ordering Platform — API docs</strong>
        <span style={{ marginLeft: "0.75rem", color: "#666" }}>
          Admin routes: log in below (Admin — Auth → POST /api/admin/auth/login → Try it out), then every
          other admin call in this page carries the session cookie automatically.
        </span>
      </div>
      <div ref={containerRef} />
    </main>
  );
}
